# Generated by Django 3.0.7 on 2020-08-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=12)),
                ('phone', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(max_length=250)),
                ('comment', models.CharField(max_length=250)),
                ('reply', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
